"""create training_executions table

Revision ID: 7b868150e879
Revises: 7c3b81bd8380
Create Date: 2026-02-14 22:54:10.810382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b868150e879'
down_revision: Union[str, Sequence[str], None] = '7c3b81bd8380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_session_id', sa.Integer(), nullable=False),
    sa.Column('training_plan_exercise_id', sa.Integer(), nullable=False),
    sa.Column('sets_done', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['training_plan_exercise_id'], ['training_plan_exercises.id'], ),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_executions_id'), 'training_executions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_executions_id'), table_name='training_executions')
    op.drop_table('training_executions')
    # ### end Alembic commands ###
